defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

args:
  type: "CFD" # "advection"/"ReacDiff"/"burgers"/"CFD"
  dim: 2
  bd: "periodic"
  nbatch: 250
  savedir: "./save/2D/CFD/"
